# Copyright IBM Corp All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

required = [
    "golang.org/x/lint/golint",
    "golang.org/x/tools/cmd/goimports",
    "github.com/golang/protobuf/protoc-gen-go",
]

ignored = [
]

noverify = [
    "github.com/grpc-ecosystem/go-grpc-middleware"
]

[[constraint]]
  name = "github.com/Knetic/govaluate"
  version = "3.0.0"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.19.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "=1.3.0"

# Pinned in support of go-dockerclient
[[override]]
  name = "github.com/docker/docker"
  revision = "0c5f8d2b9b23ab8d23529b3effdcf53bb058298c"

# Pinned in support of go-dockerclient
[[override]]
  name = "github.com/docker/libnetwork"
  revision = "19279f0492417475b6bfbd0aa529f73e8f178fb5"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/hyperledger/fabric-amcl"

[[constraint]]
  name = "github.com/hyperledger/fabric-lib-go"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"

[[constraint]]
  name = "github.com/miekg/pkcs11"
  version = "v1.0.2"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "v1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/op/go-logging"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  revision = "1967d93db724f4a5c0e101307e96d82ff520a067"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/lint"
  revision = "c67002cb31c3a748b7688c27f20d8358b4193582"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  name = "golang.org/x/tools"
  revision = "f60e5f99f0816fc2d9ecb338008ea420248d2943"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.15.0"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"
  version = "1.0.22"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2"

[[constraint]]
  branch = "master"
  name = "github.com/tedsuo/ifrit"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  revision = "a3b6351eb1ff8e1bfa30b2f55d7e282186ed8fee"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.2"

[[constraint]]
  name = "go.etcd.io/etcd"
  revision = "23731bf9ba556867089a9cc8db5e492ca6035fe8"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/sykesm/zap-logfmt"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[[constraint]]
  name = "github.com/willf/bitset"
  version = "1.1.8"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
      name = "github.com/onsi/ginkgo"
      unused-packages = false

  [[prune.project]]
      name = "github.com/onsi/gomega"
      unused-packages = false

  [[prune.project]]
      name = "go.etcd.io/etcd"
      non-go = false

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"
